#!/usr/bin/env python3
"""
Chain-of-thought vs. direct prompting for the DAMSL + Beads discourse tagger
(paper extension item #2).

Reuses the EXACT codebook, system prompt, model, and per-request chunking of
the existing direct-prompt tagger (05_linguistic/tag_llm.py, which produced
outputs/llm_tags.csv), on a matched stratified sample, so the only thing that
differs between "direct" and "CoT" is one schema field: a free-text
`reasoning` string that the model must write, per sentence, BEFORE its
`damsl`/`beads` codes (structured outputs generate fields in schema order, so
this forces the reasoning tokens to precede the label tokens rather than
follow them).

Sample: a fixed-seed, per-debate-proportional stratified sample of the 24,193
candidate sentences across the 24 debates used throughout the paper (matches
llm_ext_data.py's EXCLUDE_DEBATES), sized ~3,000 sentences --- large enough
for a stable Krippendorff's alpha, small enough to keep this a genuinely
"near-free" addition next to the 35,460-sentence direct run already on file.

Requires: ANTHROPIC_API_KEY.
Usage:
    python run_cot_tagging.py --prompt-only     # just write cot_tagging_prompt.md
    python run_cot_tagging.py                    # full run / resume
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import sys
import threading
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, "/Users/lavanya/debate_analysis/05_linguistic")
import anthropic
from tag_llm import SYSTEM, DAMSL_CODES, BEADS_CODES, MODEL, CHUNK, MAX_TOKENS  # noqa: E402

PROJECT = Path("/Users/lavanya/debate_analysis")
MASTER = PROJECT / "outputs" / "master_sentences.csv"
PROMPT_MD = PROJECT / "Sahana Project" / "cot_tagging_prompt.md"
HERE = Path(__file__).resolve().parent
SAMPLE_CSV = HERE / "cot_sample_ids.csv"
OUT_PARTIAL = HERE / "cot_tags_partial.csv"
OUT_CSV = HERE / "cot_tags.csv"

EXCLUDE_DEBATES = {"1034", "1036"}
SAMPLE_FRACTION = 0.124  # ~3,000 of 24,193
SEED = 20260806

SCHEMA_COT = {
    "type": "object",
    "properties": {
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "sentence_id": {"type": "string"},
                    "reasoning": {
                        "type": "string",
                        "description": "1-2 sentences of reasoning about the discourse "
                                        "act and any rhetorical bias, written BEFORE "
                                        "you decide the codes.",
                    },
                    "damsl": {"type": "array", "items": {"type": "string", "enum": DAMSL_CODES}},
                    "beads": {"type": "array", "items": {"type": "string", "enum": BEADS_CODES}},
                },
                "required": ["sentence_id", "reasoning", "damsl", "beads"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["results"],
    "additionalProperties": False,
}


def build_sample():
    if SAMPLE_CSV.exists():
        with SAMPLE_CSV.open() as f:
            return [(r["sentence_id"], r["sentence_text"]) for r in csv.DictReader(f)]

    by_debate = defaultdict(list)
    with MASTER.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["speaker_role"] != "candidate":
                continue
            if row["debate_audio_id"] in EXCLUDE_DEBATES:
                continue
            txt = (row["sentence_text"] or "").strip()
            if txt:
                by_debate[row["debate_audio_id"]].append((row["sentence_id"], txt))

    rng = random.Random(SEED)
    sample = []
    for d, rows in by_debate.items():
        k = max(1, round(len(rows) * SAMPLE_FRACTION))
        sample.extend(rng.sample(rows, k))
    rng.shuffle(sample)

    with SAMPLE_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sentence_id", "sentence_text"])
        w.writerows(sample)
    print(f"[sample] {len(sample):,} sentences across {len(by_debate)} debates -> {SAMPLE_CSV}")
    return sample


def write_prompt_md():
    PROMPT_MD.parent.mkdir(parents=True, exist_ok=True)
    md = (
        "# Chain-of-thought tagging prompt --- CoT-vs-Direct comparison (extension #2)\n\n"
        f"Generated by `run_cot_tagging.py`. Model: **{MODEL}** (same as the direct "
        f"tagger), Anthropic Messages API, {CHUNK} sentences per request, structured "
        "(json_schema) outputs.\n\n"
        "Identical codebook and system prompt to the direct tagger "
        "(`05_linguistic/tag_llm.py`, `tagging_prompt.md`) --- the only difference is "
        "one added schema field, `reasoning`, which the model must fill in BEFORE "
        "`damsl`/`beads` for each sentence.\n\n"
        f"Sample: a fixed-seed (`{SEED}`) per-debate-proportional stratified sample "
        f"of the same 24-debate, candidate-only sentence pool used throughout the "
        f"paper, at {SAMPLE_FRACTION:.1%} (~3,000 sentences). The DIRECT-prompt "
        "comparison numbers use the pre-existing `outputs/llm_tags.csv` results "
        "restricted to the identical sample, so both conditions are scored on "
        "exactly the same sentences.\n\n"
        "## System prompt (verbatim, identical to the direct tagger)\n\n```\n" + SYSTEM + "\n```\n\n"
        "## CoT JSON schema\n\n```json\n" + json.dumps(SCHEMA_COT, indent=2) + "\n```\n"
    )
    PROMPT_MD.write_text(md)
    print(f"[write] {PROMPT_MD}")


def load_done():
    if not OUT_PARTIAL.exists():
        return set()
    with OUT_PARTIAL.open() as f:
        return {r["sentence_id"] for r in csv.DictReader(f)}


_lock = threading.Lock()


def tag_chunk(client, chunk):
    listing = "\n".join(f"[{sid}] {txt}" for sid, txt in chunk)
    resp = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=[{"type": "text", "text": SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": "Tag these sentences:\n" + listing}],
        output_config={"format": {"type": "json_schema", "schema": SCHEMA_COT}},
    )
    text = next((b.text for b in resp.content if b.type == "text"), "")
    out = {}
    for item in json.loads(text).get("results", []):
        sid = item.get("sentence_id")
        if sid:
            dset, bset = set(item.get("damsl", [])), set(item.get("beads", []))
            out[sid] = (
                item.get("reasoning", ""),
                [c for c in DAMSL_CODES if c in dset],
                [c for c in BEADS_CODES if c in bset],
            )
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--prompt-only", action="store_true")
    args = ap.parse_args()

    write_prompt_md()
    if args.prompt_only:
        return

    client = anthropic.Anthropic()
    sentences = build_sample()
    done = load_done()
    todo = [(sid, txt) for sid, txt in sentences if sid not in done]
    chunks = [todo[i:i + CHUNK] for i in range(0, len(todo), CHUNK)]
    print(f"[cot] {len(sentences):,} sample sentences, {len(done):,} already done, "
          f"{len(todo):,} to tag -> {len(chunks):,} chunks, {args.workers} workers")

    new = not OUT_PARTIAL.exists()
    pf = OUT_PARTIAL.open("a", newline="")
    pw = csv.writer(pf)
    if new:
        pw.writerow(["sentence_id", "reasoning", "damsl_tags", "beads_tags", "n_damsl_tags", "n_beads_tags"])
        pf.flush()

    completed = 0
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = {ex.submit(tag_chunk, client, ch): ch for ch in chunks}
        for fut in as_completed(futs):
            ch = futs[fut]
            try:
                res = fut.result()
            except Exception as e:
                print(f"[warn] chunk failed ({ch[0][0]}...): {e}")
                continue
            with _lock:
                for sid, txt in ch:
                    reasoning, d, b = res.get(sid, ("", [], []))
                    pw.writerow([sid, reasoning, "; ".join(d), "; ".join(b), len(d), len(b)])
                pf.flush()
            completed += 1
            if completed % 25 == 0:
                print(f"  {completed}/{len(chunks)} chunks done")
    pf.close()

    rows = {r["sentence_id"]: r for r in csv.DictReader(OUT_PARTIAL.open(newline=""))}
    with OUT_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sentence_id", "reasoning", "damsl_tags", "beads_tags", "n_damsl_tags", "n_beads_tags"])
        for sid, _ in sentences:
            r = rows.get(sid, {})
            w.writerow([sid, r.get("reasoning", ""), r.get("damsl_tags", ""), r.get("beads_tags", ""),
                        r.get("n_damsl_tags", "0"), r.get("n_beads_tags", "0")])
    print(f"[write] {OUT_CSV} ({len(sentences):,} rows)")


if __name__ == "__main__":
    main()
